const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('../apps/web/node_modules/typescript');
const source = fs.readFileSync(require('node:path').join(__dirname, '../apps/web/src/components/Map/useTwinQueue.ts'), 'utf8');
const compiled = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const context = {exports:{},require:()=>({})};
vm.runInNewContext(compiled,context);
const status=context.exports.selectionStatus;
const job={id:'test',project:'fixture',plan_id:'plan',status:'running',categories:{selection:{status:'succeeded',stages:{validation:{status:'succeeded'}}}}};
assert.equal(status(job,'selection'),'Validated · awaiting publication');
assert.equal(status({...job,status:'awaiting_approval'},'selection'),'Awaiting approval');
assert.equal(status({...job,status:'failed'},'selection'),'Not published · job failed');
assert.equal(status({...job,status:'cancelled'},'selection'),'Cancelled');
assert.equal(status({...job,status:'cancelling'},'selection'),'Cancelling');
assert.equal(status({...job,status:'succeeded'},'selection'),'Published');
assert.equal(status({...job,status:'pending',categories:{}},'selection'),'Queued');
assert.equal(status({...job,categories:{selection:{status:'running',stages:{fetch:{status:'running'}}}}},'selection'),'Downloading');
console.log('8 queue publication/status checks passed');
